{{- if eq .Values.service.type "ClusterIP" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "rancher.fullname" . }}-grpc
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    field.cattle.io/rancher-server-ingress: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
{{- if .Values.ingress.configurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- template "configurationSnippet" . }}
{{- end }}
{{- if eq .Values.tls "external" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
{{- end }}
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.hostname }}  # hostname to access rancher server
    http:
      paths:
      - path: /thanos.Store
        backend:
          serviceName: {{ template "rancher.fullname" . }}
          servicePort: 50051
{{- if eq .Values.tls "ingress" }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: tls-rancher-ingress
{{- end }}
{{- end }}
